mqtt:
  enabled: false

model:
  path: /config/model/best_float32.tflite
  labelmap_path: /config/model/labelmap.txt
  model_type: ssd  # غيرناها لـ ssd عشان الموديل ده SSD
  width: 300
  height: 300

cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/videos/veo3_construction.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - helmet
        - vest

