mqtt:
  enabled: false
  host: 127.0.0.1

detectors:
  onnx:
    type: onnx

model:
  model_type: yolo-generic
  width: 320
  height: 320
  input_tensor: nchw
  input_dtype: float
  path: /config/model/best.onnx
  labelmap_path: /config/model/labelmap.txt

snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
  retain:
    default: 1

cameras:
  test_video:
    ffmpeg:
      inputs:
        - path: /media/frigate/videos/veo3_construction.mp4
          input_args: "-re -stream_loop -1 -fflags +genpts"
          roles:
            - detect
    detect:
      enabled: true
      width: 362
      height: 398
      fps: 5
    objects:
      track:
        - "Safety-Helmet"
        - "Reflective-Jacket"
      filters:
        Safety-Helmet:
          min_score: 0.15
          threshold: 0.25
        Reflective-Jacket:
          min_score: 0.15
          threshold: 0.25
version: 0.16-0
