mqtt:
  enabled: false

detectors:
  onnx:
    type: onnx
    device: CPU  # or GPU if you have CUDA support
    num_threads: 3  # Adjust based on your CPU cores

model:
  path: /config/model/best_10C_uint8.onnx
  labelmap_path: /config/model/labelmap.txt
  model_type: yolo-generic   # غيرناها لـ ssd عشان الموديل ده SSD
  width: 640
  height: 640
  input_tensor: nchw          # ✅ Add this - channels first
  input_pixel_format: rgb     # ✅ Add this - RGB format

cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/videos/hardhat.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
    detect:
      enabled: true
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - Person
        - Hardhat
        - NO-Hardhat
        - Safety Vest
        - NO-Safety Vest
        - Mask
        - NO-Mask
        - machinery
        - vehicle
        - Safety Cone
detect:
  enabled: true
version: 0.16-0
