mqtt:
  enabled: false
  host: 127.0.0.1

detectors:
  cpu1:
    type: cpu

model:
  path: /config/model/best_float32.tflite
  width: 362
  height: 398
  input_tensor: nchw
  input_pixel_format: rgb
  labelmap_path: /config/model/labelmap.txt

objects:
  track:
    - Safety-Helmet
    - Reflective-Jacket

cameras:
  test_video:
    ffmpeg:
      inputs:
        - path: /media/frigate/videos/veo3_construction.mp4
          input_args: "-re -stream_loop -1 -fflags +genpts"
          roles:
            - detect
    detect:
      enabled: true
      width: 362
      height: 398
      fps: 5

version: 0.16-0